Running Move unit tests
[ PASS    ] 0x1::M::no_timeout
[ FAIL    ] 0x1::M::no_timeout_fail
[ PASS    ] 0x1::M::no_timeout_while_loop
[ FAIL    ] 0x1::M::timeout_fail
[ PASS    ] 0x1::M::timeout_fail_with_expected_failure

Test failures:

Failures in 0x1::M:

┌── no_timeout_fail ──────
│ Test was not expected to error, but it aborted with code 0 originating in an unknown location rooted here
└──────────────────


┌── timeout_fail ──────
│ Failed to run a program on Solana VM.
│ 
│ 
│ Err(ExceededMaxInstructions(110))
└──────────────────

Test result: FAILED. Total tests: 5; passed: 3; failed: 2
